---
{#File: ubuntu_autoremove_packages_template.yaml#}
{#Author: Vukasin Koprivica#}
{#1. Email notification to distribution list before removal of unnacessary packages begins. #}
{#It is required to free space from boot partition in order for successful installation#}
{#of future packages. #}
{#2. Pause of 5 minutes for current users of the servers to log out.#}
{#3. Remove unnecessary linux boot packages.#}
{#4. Reboot server.#}
{#5. Pause of 5 minutes for server to boot. #}
{#6. Check disk space.#}
{#7. Email notification to distribution list about free boot disk space.#}
###
- hosts: host_group
  tasks:
    - name: Email Report
      mail:
        host: smtp.domain.com
        port: 25
        from: <ansible_server@domain.com>
        to: <email@domain.com>
        subject: Linux Boot Partition Report
        body: "Boot partition cleanup of the following Linux servers
will start in 5 munutes: {{ ansible_hostname}}.\nPlease LOG OUT immediately if you are using any of servers!"

    - pause: seconds=300

    - name: Remove Unnecessary Linux Boot Packages
      become: yes
      become_method: sudo
      apt:
        autoremove: yes


    - name: Reboot Server
      become: yes
      become_method: sudo
      command: /sbin/shutdown -r +1

    - pause: seconds=300

    - name: Check Disk Space
      shell: df -l
      register: result
    - debug: var=result.stdout_lines[7]


    - name: Email Report
      mail:
        host: smtp.domain.com
        port: 25
        from: <ansible_server@domain.com>
        to: <email@domain.com>
        subject: Linux Boot Partition Report
        body: " Boot partition cleanup was completed.\n
Server {{ansible_hostname}} was rebooted.\n
Current {{ansible_hostname}} boot partition report:   {{result.stdout_lines[7]}}"
